Added option to use Breeze Dark only if the client's dark mode is ena…
mwalbeck/nextcloud-breeze-dark pull request #276
Opened 2021-10-23 19:36 UTC by untbu

Added option to make Breeze Dark dependent on prefers-color-scheme css media query

2021-10-31 09:59 UTC, mwalbeck requested changes
Thank you very much for the contribution! From my testing, it works quite well! I did find a couple minor things, but overall I'm quite happy with it.

If you could fix the mentioned issues and squash the pr into one commit, then I think it's ready to merge!

2021-10-31 09:59 UTC, mwalbeck commented on lib/Settings/Admin.php
> +        $themeAutomaticActivation = $this->config->getAppValue($this->appName, 'theme_automatic_activation_enabled', "1");
The default value here should be "0" instead of "1"

2021-10-31 09:59 UTC, mwalbeck commented on lib/Settings/Personal.php
> +        $defaultAutomaticActivation = $this->config->getAppValue($this->appName, 'theme_automatic_activation_enabled', "1");
The default value should also be "0" here

2021-10-31 09:59 UTC, mwalbeck commented on lib/Settings/Personal.php
> +        $themeAutomaticActivation = $this->config->getUserValue($this->userId, $this->appName, 'theme_automatic_activation_enabled', $default);
Looks like you forgot to replace `$default` with `$defaultAutomaticActivation`

2021-10-31 09:59 UTC, mwalbeck commented on CHANGELOG.md
> +-   Add option to use Breeze Dark only if the client's dark mode is enabled
Could you add the following to the changelog line, like it's done on previous entries

`[#98](https://github.com/mwalbeck/nextcloud-breeze-dark/issues/98)`

2021-10-31 20:08 UTC, untbu commented
Sorry, but i don't know how to squash the commits. When i do it locally, i get an error while pushing it and on github i dont' even see the commits in my fork. Don't you have an option to squash and merge?

2021-11-01 09:50 UTC, mwalbeck approved these changes

2021-11-01 09:54 UTC, mwalbeck commented
No worries! I generally prefer to let the committer do the squashing and commit message, but it's no more than a preference.

Thank you again for the contribution! I greatly appreciate it!

Cheers!

2021-11-01 09:59 UTC, merged